### ISSUE TITLE
redirect to/from login form

### ISSUE THREAD

**Issue by twachtler** [G-Node/GCA-Web#361]
- when clicking "login" on a page, the site should continue at this page after login
- when trying to access a page without authentication, the user should be redirected to the login page, and then continue at this page after login

**Comment by mpsonntag** [comment]
ad 2) I would not redirect a user from an unauthorized page since we do not provide any link on the page to a page which requires authentication if a user is not logged in. Especially since a user might try to access a page that the user is not able to access even after login. This would then redirect back and forth between login page an page the user has no access to.
On a related note: the 'unauthorized' page display was kind of broken, which I did fix. So any user trying to access a restricted site now has the option to manually move to the login page or a different page of their choosing.

**Comment by mpsonntag** [comment]
ad 2) In the discussion the use case came up, that a user might want to send a link of an abstract `inPreparation` to a collaborator that is also owner of the abstract. In this case we have a link where it makes sense to forward a non-logged in user to the login page and redirect back to the edit-abstract page.
